techet_pipech
DKrakhmalyov/HSE-Course_2sem pull request #44
Opened 2021-04-17 20:47 UTC by timonchiks

2021-04-18 14:03 UTC, DKrakhmalyov commented
Советую поработать над именованием объектов, код становится нечитаемым из-за того, что непонятно, какой объект чёто делает. 
Что происходит с итератором, если его инкрементируют на последней инициализированной позиции?
При удалении массива возникнет утечка памяти

Пока могу поставить 6/10, советую привести код в порядок и замечания исправить

2021-04-30 17:04 UTC, lgAshanl commented
/tmp/checkdz/HSE-Course_2sem/homework-2/static_array.h: In member function ‘static_array<T, sz>::iterator static_array<T, sz>::begin() [with T = int; long unsigned int sz = 10]’:
/tmp/checkdz/HSE-Course_2sem/homework-2/static_array.h:165:5: warning: control reaches end of non-void function [-Wreturn-type]
  165 |     }
      |     ^
/tmp/checkdz/HSE-Course_2sem/homework-2/static_array.h: In member function ‘static_array<T, sz>::iterator static_array<T, sz>::end() [with T = int; long unsigned int sz = 10]’:
/tmp/checkdz/HSE-Course_2sem/homework-2/static_array.h:173:5: warning: control reaches end of non-void function [-Wreturn-type]
  173 |     }
      |     ^
/tmp/checkdz/HSE-Course_2sem/homework-2/static_array.h: In member function ‘static_array<T, sz>::iterator static_array<T, sz>::end() [with T = B; long unsigned int sz = 0]’:
/tmp/checkdz/HSE-Course_2sem/homework-2/static_array.h:173:5: warning: control reaches end of non-void function [-Wreturn-type]
  173 |     }
      |     ^
/tmp/checkdz/HSE-Course_2sem/homework-2/static_array.h: In member function ‘static_array<T, sz>::iterator static_array<T, sz>::begin() [with T = B; long unsigned int sz = 0]’:
/tmp/checkdz/HSE-Course_2sem/homework-2/static_array.h:165:5: warning: control reaches end of non-void function [-Wreturn-type]
  165 |     }
      |     ^

2021-04-30 17:22 UTC, lgAshanl requested changes

2021-04-30 17:22 UTC, lgAshanl commented on homework-2/static_array.h
> +            papasha = g.papasha;
Да, с именованием остались проблемы

2021-04-30 17:22 UTC, lgAshanl commented on homework-2/static_array.h
> +    bool fuul = false;
???

2021-04-30 17:22 UTC, lgAshanl commented on homework-2/static_array.h
> +        throw(-1);
"Что происходит с итератором, если его инкрементируют на последней инициализированной позиции?" - не зря Денис это спросил. end() должен указывать "за пределы" контейнера. Как бы указывать на элемент следующий за последним. По end() нельзя читать, но с ним можно сравниваться. Т.е. тебе надо итератор пересмотреть в целом и здесь не надо кидать исключение, а надо возвращать итератор

2021-05-27 21:31 UTC, closed without merging